ALTER TABLE "properties" ADD COLUMN "is_demo" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "projects" ADD COLUMN "is_demo" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "developers" ADD COLUMN "is_demo" BOOLEAN NOT NULL DEFAULT false;
