export const ROUTES = {
  HOME: "/",
  SIGNUP: "/signup",
  SIGNIN: "/signin",
  CONTACT: "/contact",
  PROPERTIES: "/properties",
  PROPERTY: (id: string) => `/properties/${id}`,
  PROPERTY_NEW: "/properties/new",
  PROPERTY_EDIT: (id: string) => `/properties/${id}/edit`,
  DASHBOARD: "/dashboard",
  PROJECTS: "/projects",
  PROJECT: (slug: string) => `/projects/${slug}`,
  DEVELOPERS: "/developers",
  DEVELOPER: (slug: string) => `/developers/${slug}`,
  ADMIN: "/admin",
  ADMIN_LISTINGS: "/admin/listings",
  ADMIN_USERS: "/admin/users",
  ADMIN_SETTINGS: "/admin/settings",
  ADMIN_PROJECTS: "/admin/projects",
  ADMIN_PROJECT_NEW: "/admin/projects/new",
  ADMIN_PROJECT_EDIT: (id: string) => `/admin/projects/${id}/edit`,
  ADMIN_DEVELOPERS: "/admin/developers",
  ADMIN_LEADS: "/admin/leads",
  VERIFY_EMAIL: "/verify-email",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  UNAUTHORIZED: "/unauthorized",
} as const;
