export const ROUTES = {
  HOME: "/",
  SIGNUP: "/signup",
  SIGNIN: "/signin",
  CONTACT: "/contact",
  PROPERTIES: "/properties",
  PROPERTY: (id: string) => `/properties/${id}`,
  PROPERTY_NEW: "/properties/new",
  PROPERTY_EDIT: (id: string) => `/properties/${id}/edit`,
  DASHBOARD: "/dashboard",
  VERIFY_EMAIL: "/verify-email",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  UNAUTHORIZED: "/unauthorized",
} as const;
