export const ROUTES = {
  HOME: '/',
  SIGNUP: '/signup',
  SIGNIN: '/signin',
  ADMIN: '/admin',
  UNAUTHORIZED: '/unauthorized',
  CONTACT: '/contact',
  PROPERTIES: '/properties',
  PROPERTY: '/properties/:id',
  PARTNERS: '/partners',
  VERIFY_EMAIL: '/verify-email',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  DASHBOARD: '/dashboard',
  AUTH_SUCCESS: '/auth/success',
  AUTH_ERROR: '/auth/error',
  ADD_PASSWORD: '/add-password',
} as const
